import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import BannerSection from "./components/mainSection";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <BannerSection />
      </body>
    </html>
  );
}
